# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200806_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
