# Generated by Django 6.0.7 on 2026-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_auto_20200807_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_logo",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="song",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
